name: Prerequisites with pull
on:
  workflow_dispatch:
    inputs:
      REPO_ORG:
        description: 'Organization of the repo to pull'
        required: true
        default: 'andreixu'
      REPO_NAME:
        description: 'Name of the repo to pull'
        required: true
        default: 'updater'

jobs:
  pull-same-org-repo:
    name: Pull from repo in same org via prerequisites script
    runs-on: ubuntu-latest
    steps:
      - name: Summary message
        id: summary-message
        shell: bash
        run: |
          echo "## Pull from Repo from same org Demo" >> $GITHUB_STEP_SUMMARY
      - name: Pull current repo
        id: pull-repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Check for prerequisites
        id: prerequisites
        shell: bash
        env:
          REPO_ORG: ${{ github.event.inputs.REPO_ORG }}
          REPO_NAME: ${{ github.event.inputs.REPO_NAME }}
        run: |
          echo "### Prerequisites 📋  " >> $GITHUB_STEP_SUMMARY
          if [[ -f ./prerequisites.sh && -x ./prerequisites.sh ]]; then
            echo "▶️ Prerequisites script found. Execution logs bellow:" >> $GITHUB_STEP_SUMMARY
            ./prerequisites.sh
          else
            echo "⏹️ No prerequisites found." >> $GITHUB_STEP_SUMMARY
          fi